//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_TheCargoDetail
    {
        public int theCargoDetailID { get; set; }
        public string lOTNO { get; set; }
        public Nullable<int> staffID { get; set; }
        public Nullable<int> materialsAreID { get; set; }
        public Nullable<int> amount { get; set; }
        public string source { get; set; }
        public string phone { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> money { get; set; }
        public string remark { get; set; }
    }
}
