//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CYGLXTEntities : DbContext
    {
        public CYGLXTEntities()
            : base("name=CYGLXTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_EatInRecord> B_EatInRecord { get; set; }
        public virtual DbSet<B_Order> B_Order { get; set; }
        public virtual DbSet<B_Orderdetails> B_Orderdetails { get; set; }
        public virtual DbSet<B_OutboundList> B_OutboundList { get; set; }
        public virtual DbSet<B_TheCargoDetail> B_TheCargoDetail { get; set; }
        public virtual DbSet<B_VIPConsumptionDetails> B_VIPConsumptionDetails { get; set; }
        public virtual DbSet<R_JurisdictionGroupModule> R_JurisdictionGroupModule { get; set; }
        public virtual DbSet<R_JurisdictionGroupUser> R_JurisdictionGroupUser { get; set; }
        public virtual DbSet<S_Account> S_Account { get; set; }
        public virtual DbSet<S_AmountOfDetail> S_AmountOfDetail { get; set; }
        public virtual DbSet<S_DiningTable> S_DiningTable { get; set; }
        public virtual DbSet<S_FinancialSubsidiary> S_FinancialSubsidiary { get; set; }
        public virtual DbSet<S_Information> S_Information { get; set; }
        public virtual DbSet<S_JurisdictionGroup> S_JurisdictionGroup { get; set; }
        public virtual DbSet<S_JurisdictionModule> S_JurisdictionModule { get; set; }
        public virtual DbSet<S_MaterialsAre> S_MaterialsAre { get; set; }
        public virtual DbSet<S_Member> S_Member { get; set; }
        public virtual DbSet<S_Menu> S_Menu { get; set; }
        public virtual DbSet<S_Staff> S_Staff { get; set; }
        public virtual DbSet<S_TheLoginDetails> S_TheLoginDetails { get; set; }
        public virtual DbSet<S_TInventory> S_TInventory { get; set; }
        public virtual DbSet<S_VIP> S_VIP { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
