//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_JurisdictionGroupModule
    {
        public int jurisdictionGroupModuleID { get; set; }
        public Nullable<int> jurisdictionGroupID { get; set; }
        public Nullable<int> moduleID { get; set; }
    }
}
