//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_DiningTable
    {
        public int diningTableID { get; set; }
        public string tableNumber { get; set; }
        public Nullable<int> number { get; set; }
        public string status { get; set; }
        public string affiliation { get; set; }
        public Nullable<decimal> totalMoney { get; set; }
        public Nullable<int> orderID { get; set; }
    }
}
