//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Information
    {
        public int InformationID { get; set; }
        public Nullable<int> staffSendID { get; set; }
        public Nullable<int> staffReceiveID { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> postTime { get; set; }
        public string sendContent { get; set; }
        public string status { get; set; }
        public Nullable<bool> staffIDview { get; set; }
        public Nullable<bool> staffIDNview { get; set; }
    }
}
