//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Menu
    {
        public int menuID { get; set; }
        public string dishes { get; set; }
        public Nullable<decimal> price { get; set; }
        public string picture { get; set; }
        public string cuisine { get; set; }
        public Nullable<bool> effective { get; set; }
    }
}
