//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Staff
    {
        public int staffID { get; set; }
        public string EMPNO { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string IDNumber { get; set; }
        public string sex { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public Nullable<System.DateTime> departureDate { get; set; }
        public string statust { get; set; }
        public string address { get; set; }
        public byte[] picture { get; set; }
    }
}
