//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_TheLoginDetails
    {
        public int theLoginDetailsID { get; set; }
        public Nullable<int> staffID { get; set; }
        public Nullable<System.DateTime> logonTime { get; set; }
        public Nullable<System.DateTime> offlineTime { get; set; }
        public string theLogin { get; set; }
    }
}
