//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYGLXTStudent.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_VIP
    {
        public int VIPID { get; set; }
        public Nullable<int> memberID { get; set; }
        public string name { get; set; }
        public string cardNo { get; set; }
        public Nullable<decimal> availableBalance { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public Nullable<decimal> Integral { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> openingTime { get; set; }
    }
}
